-- AlterTable
ALTER TABLE "Attendance" ADD COLUMN     "courseCode" TEXT,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "checkIn" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "course" DROP NOT NULL;
